import '../models/policy.dart';

class MockData {
  static List<InsurancePolicy> healthPolicies = [
    InsurancePolicy(
      id: '1',
      name: 'Health Plus Family Floater',
      provider: 'Star Health',
      category: 'health',
      sumAssured: 500000,
      premium: 8500,
      premiumType: 'Yearly',
      benefits: ['Cashless Hospitalization', 'Pre & Post Hospitalization', 'Day Care Procedures', 'Ambulance Cover'],
      features: ['No Room Rent Cap', 'Restore Benefit', 'Annual Health Checkup', 'Maternity Cover'],
      claimSettlementRatio: 95.5,
      waitingPeriod: 30,
      policyTerm: 1,
      rating: 4.5,
      reviews: 1250,
    ),
    InsurancePolicy(
      id: '2',
      name: 'Optima Secure',
      provider: 'HDFC Ergo',
      category: 'health',
      sumAssured: 1000000,
      premium: 12500,
      premiumType: 'Yearly',
      benefits: ['Cashless Treatment', 'Pre Hospitalization (60 days)', 'Post Hospitalization (180 days)', 'AYUSH Cover'],
      features: ['2x Multiplier Benefit', 'No Sub-limits', 'Home Hospitalization', 'Mental Health Cover'],
      claimSettlementRatio: 97.2,
      waitingPeriod: 30,
      policyTerm: 1,
      rating: 4.7,
      reviews: 2100,
    ),
    InsurancePolicy(
      id: '3',
      name: 'Care Supreme',
      provider: 'Care Health',
      category: 'health',
      sumAssured: 750000,
      premium: 9200,
      premiumType: 'Yearly',
      benefits: ['Hospitalization Cover', 'ICU Charges', 'Medicine Costs', 'Diagnostic Tests'],
      features: ['Unlimited Recharge', 'No Claim Bonus', 'Free Health Checkup', 'Teleconsultation'],
      claimSettlementRatio: 94.8,
      waitingPeriod: 30,
      policyTerm: 1,
      rating: 4.4,
      reviews: 890,
    ),
    InsurancePolicy(
      id: '4',
      name: 'Activ Assure Diamond',
      provider: 'Aditya Birla',
      category: 'health',
      sumAssured: 1500000,
      premium: 15600,
      premiumType: 'Yearly',
      benefits: ['Hospitalization', 'Day Care', 'Domiciliary', 'Organ Donor'],
      features: ['Chronic Management', 'HealthReturns', 'Second Opinion', 'International Cover'],
      claimSettlementRatio: 96.1,
      waitingPeriod: 30,
      policyTerm: 1,
      rating: 4.6,
      reviews: 1560,
    ),
  ];

  static List<InsurancePolicy> lifePolicies = [
    InsurancePolicy(
      id: '5',
      name: 'Jeevan Labh',
      provider: 'LIC',
      category: 'life',
      sumAssured: 2000000,
      premium: 18000,
      premiumType: 'Yearly',
      benefits: ['Death Benefit', 'Maturity Benefit', 'Bonus', 'Loan Facility'],
      features: ['Limited Premium', 'High Returns', 'Tax Benefits', 'Loan Against Policy'],
      claimSettlementRatio: 98.5,
      policyTerm: 16,
      rating: 4.8,
      reviews: 3200,
    ),
    InsurancePolicy(
      id: '6',
      name: 'Click 2 Protect',
      provider: 'HDFC Life',
      category: 'life',
      sumAssured: 1000000,
      premium: 7500,
      premiumType: 'Yearly',
      benefits: ['Death Cover', 'Accidental Death', 'Critical Illness', 'Waiver of Premium'],
      features: ['Return of Premium', 'Flexible Payout', 'Tax Benefits', 'Online Discount'],
      claimSettlementRatio: 98.2,
      policyTerm: 20,
      rating: 4.6,
      reviews: 2100,
    ),
  ];

  static List<InsurancePolicy> motorPolicies = [
    InsurancePolicy(
      id: '7',
      name: 'Comprehensive Car Insurance',
      provider: 'ICICI Lombard',
      category: 'motor',
      sumAssured: 500000,
      premium: 8500,
      premiumType: 'Yearly',
      benefits: ['Own Damage', 'Third Party', 'Theft Cover', 'Natural Calamities'],
      features: ['Zero Depreciation', 'Roadside Assistance', 'Engine Protection', 'NCB Protection'],
      claimSettlementRatio: 93.5,
      rating: 4.3,
      reviews: 4500,
    ),
    InsurancePolicy(
      id: '8',
      name: 'Bike Shield Premium',
      provider: 'Bajaj Allianz',
      category: 'motor',
      sumAssured: 150000,
      premium: 2800,
      premiumType: 'Yearly',
      benefits: ['Accident Cover', 'Theft Protection', 'Third Party', 'Fire & Explosion'],
      features: ['24x7 Spot Assistance', 'Nil Depreciation', 'Engine Cover', 'Consumables Cover'],
      claimSettlementRatio: 94.2,
      rating: 4.4,
      reviews: 3200,
    ),
  ];

  static List<Provider> providers = [
    Provider(
      id: '1',
      name: 'Star Health',
      logoUrl: '',
      claimSettlementRatio: 95.5,
      networkHospitals: 14000,
      rating: 4.5,
    ),
    Provider(
      id: '2',
      name: 'HDFC Ergo',
      logoUrl: '',
      claimSettlementRatio: 97.2,
      networkHospitals: 13000,
      rating: 4.7,
    ),
    Provider(
      id: '3',
      name: 'Care Health',
      logoUrl: '',
      claimSettlementRatio: 94.8,
      networkHospitals: 16500,
      rating: 4.4,
    ),
    Provider(
      id: '4',
      name: 'LIC',
      logoUrl: '',
      claimSettlementRatio: 98.5,
      networkHospitals: 0,
      rating: 4.8,
    ),
  ];
}
